default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_crawler_development
  timeout: 5000
  host: postgres
  username: postgres
  password: postgres
  port: 5432

test:
  <<: *default
  database: ruby_crawler_test
  timeout: 5000
  host: localhost
  port: 5432

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: ruby_crawler_production
  username: ruby_crawler
  password: <%= ENV["RUBY_CRAWLER_DATABASE_PASSWORD"] %>